export const cities = [
  { name: "Алматы", title: "Алматы", uri: "", code: "almaty" },
  { name: "Астана", title: "Астане", uri: "astana", code: "astana" },
  { name: "Шымкент", title: "Шымкенте", uri: "shymkent", code: "shymkent" },
  { name: "Актау", title: "Актау", uri: "aktau", code: "aktau" },
  { name: "Актобе", title: "Актобе", uri: "aktobe", code: "aktobe" },
  { name: "Атырау", title: "Атырау", uri: "atyrau", code: "atyrau" },
  { name: "Жанаозен", title: "Жанаозене", uri: "janaozen", code: "janaozen" },
  { name: "Жезказган", title: "Жезказгане", uri: "jezkazgan", code: "jezkazgan" },
  { name: "Караганда", title: "Караганде", uri: "karaganda", code: "karaganda" },
  { name: "Кокшетау", title: "Кокшетау", uri: "kokshetau", code: "kokshetau" },
  { name: "Костанай", title: "Костанае", uri: "kostanai", code: "kostanai" },
  { name: "Кызылорда", title: "Кызылорде", uri: "kyzylorda", code: "kyzylorda" },
  { name: "Павлодар", title: "Павлодаре", uri: "pavlodar", code: "pavlodar" },
  { name: "Петропавловск", title: "Петропавловске", uri: "petropavlovsk", code: "petropavlovsk" },
  { name: "Семей", title: "Семее", uri: "semei", code: "semei" },
  { name: "Талдыкорган", title: "Талдыкоргане", uri: "taldykorgan", code: "taldykorgan" },
  { name: "Тараз", title: "Таразе", uri: "taraz", code: "taraz" },
  { name: "Туркестан", title: "Туркестане", uri: "turkestan", code: "turkestan" },
  { name: "Уральск", title: "Уральске", uri: "uralsk", code: "uralsk" },
  { name: "Усть-Каменогорск", title: "Усть-Каменогорске", uri: "ust-kamenogorsk", code: "ust-kamenogorsk" },
];
